### ISSUE TITLE
A portion of README is outdated with react-router v7

### ISSUE THREAD

**Issue by sindras** [epicweb-dev/client-hints#20]
Specifically this section in README. The json function is deprecated.

As per [this discussion](https://github.com/remix-run/react-router/discussions/12257), we can remove it. I was able to test it in my own project, and it works just fine.

BTW, thank you for creating `client-hints` - it is very convenient!

```diff
export async function loader({ request }: DataFunctionArgs) {
- return json({
+ return {
    // other stuff here...
    requestInfo: {
      hints: getHints(request),
    },
- })
+ }
}
```

**Comment by sindras** [comment]
Just noticed one more thing should also be updated in the README:

```diff
import { useRevalidator } from 'react-router';
```

**Comment by kentcdodds** [comment]
PR is welcome!

**Comment by sindras** [comment]
^ I just had a chance to make the PR, but it is not urgent though. I just realized epic-stack is still WIP towards RRv7
