### ISSUE TITLE
Type information lost on JsonifyObject (?)

### ISSUE THREAD

**Issue by ricardocosta** [epicweb-dev/client-hints#6]
Hello!

I have a project using epic-stack and I decided to apply the same changes as https://github.com/epicweb-dev/epic-stack/commit/d312d7b3604be9f467fc7f2ffe8e7c4ee81147d2 and https://github.com/epicweb-dev/epic-stack/commit/ae3f66a5296a3ed3bcf6ffd51187c4d1249dbcc3 to start using `@epic-web/client-hints`.

However, upon doing the change, `@typescript-eslint` started to complain about unsafe assignments due to `hints` being of type `any`, even though VSCode is saying `getHints` returns `ClientHintsValue<Hints>`.
<img width="631" alt="image" src="https://github.com/epicweb-dev/client-hints/assets/11922336/cb614829-3042-485e-b8df-e517c0d603b5">

The difference to the pre-`@epic-web/client-hints` usage is that `getHints` used to return a simple object:
<img width="407" alt="image" src="https://github.com/epicweb-dev/client-hints/assets/11922336/06f92107-bf6b-4ee6-99f2-01450626f556">

Looking into `getHints`, the implementation is the same in both versions, but what changes are the type definitions:
**Before**
```
{
      [name in ClientHintNames]: (typeof clientHints)[name] extends {
        transform: (value: string) => infer ReturnValue;
      }
        ? ReturnValue
        : (typeof clientHints)[name]["fallback"];
},
```

**After**
```
Hints extends Record<string, ClientHint<any>>
```

After a lot of searching, I think this is the same issue as reported by Kent here: https://github.com/sindresorhus/type-fest/issues/667
The referenced workaround is to change from `any` to `unknown` but I'm not sure if that's enough, as I tried to manually change the `.d.ts` file in `node_modules` and it didn't work.

### How to reproduce
1. Create a new project using epic-stack: `npx create-epic-app@latest`
2. Add some reference to `requestInfo.hints` in `app/utils/request-info.ts`, such as `console.log(data.requestInfo.hints)`
3. `hints` is recognized as `any` in VSCode even though it has the correct type passed into `JsonifyObject`

<img width="508" alt="image" src="https://github.com/epicweb-dev/client-hints/assets/11922336/2bee80bc-11e6-45b2-a099-9aef32ab3836">
<img width="460" alt="image" src="https://github.com/epicweb-dev/client-hints/assets/11922336/8073c691-c355-46c9-9af1-0cee508d8f5e">

**Comment by kentcdodds** [comment]
I've confirmed this issue. I definitely thought I checked this, but it looks like it's not working the way I was hoping it would which is a major bummer.

Contributions from anyone are welcome!

**Comment by kentcdodds** [comment]
I figured it out. It was improperly configured module resolution on the epic stack: https://github.com/epicweb-dev/epic-stack/commit/6a7024474e7a9031e4c38d5ddc3d5073013234e3

Sorry for the trouble!

**Comment by ricardocosta** [comment]
I applied the same config on my side and confirmed it's solved.

Thanks!
