### ISSUE TITLE
Add explicit extension to all imports

### ISSUE THREAD

**Issue by gustavopch** [epicweb-dev/client-hints#8]
That's necessary for full compatibility with ESM in TypeScript when using `"moduleResolution": "NodeNext"`.

When the import doesn't have the extension, TypeScript can't properly resolve it:
<img width="533" alt="image" src="https://github.com/epicweb-dev/client-hints/assets/10941958/2b5ea71c-6452-41d3-bfe7-23391ff4687d">

After I manually add the extension, you can see now it resolves correctly:
<img width="890" alt="image" src="https://github.com/epicweb-dev/client-hints/assets/10941958/5dad1dec-d337-4d09-af3f-1fc65dbe1670">

TypeScript doesn't modify the paths used in the imports when compiling, so it's really a matter of adding the extension to all imports in the source code.

**Comment by kentcdodds** [comment]
Yes, you're right. This is the correct thing to do in native ESM as well. I would welcome a PR to fix this!
